<a href="https://colab.research.google.com/github/Orgenes/Orgenes/blob/main/Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy, create 1-D array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
#array size
print(arr.size)

5


In [3]:
#array data type
print(arr.dtype)

int64


In [5]:
#array shape, array shape(5,) means 1-D array with 5 rows, no columns
print(arr.shape)

(5,)


In [6]:
#create a 2-D array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
#array dimemsion
print(arr2.ndim)

2


In [9]:
#array shape, (2,3) meams 2 rows, 3 columns
print(arr2.shape)


(2, 3)


In [10]:
#array type
print(type(arr2))

<class 'numpy.ndarray'>


In [ ]:
#array data type
print(arr2.dtype)